/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import model.beans.Testes;

/**
 *
 * @author Vinicius
 */
public class CriacaoTesteMDI extends javax.swing.JInternalFrame {
    /**
     * Creates new form CriacaoModMDI
     */
    public CriacaoTesteMDI() {
        initComponents();
    }
    Testes teste = new Testes();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProximo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPreTeste = new javax.swing.JLabel();
        lblPosTeste = new javax.swing.JLabel();
        pnlCriacaoModulos = new javax.swing.JPanel();
        jtCriacaoModulos = new javax.swing.JTabbedPane();
        pnlPrePosTeste = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        lblAudio = new javax.swing.JLabel();
        lblVideo = new javax.swing.JLabel();
        lblTexto_Video = new javax.swing.JLabel();
        lblVideo_Audio = new javax.swing.JLabel();
        lblTexto_Audio = new javax.swing.JLabel();
        lblVideo_img = new javax.swing.JLabel();
        lblTexto_Video_img = new javax.swing.JLabel();
        lblTexto_Audio_img = new javax.swing.JLabel();
        lblTexto_img = new javax.swing.JLabel();
        lblAudio_img = new javax.swing.JLabel();
        lblVideo_Audio_img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeTeste = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criação de Atividades (Testes)");

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPreTeste.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPreTeste.setText("Pré-Teste: ");

        lblPosTeste.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPosTeste.setText("Pós-Teste: ");

        javax.swing.GroupLayout pnlCriacaoModulosLayout = new javax.swing.GroupLayout(pnlCriacaoModulos);
        pnlCriacaoModulos.setLayout(pnlCriacaoModulosLayout);
        pnlCriacaoModulosLayout.setHorizontalGroup(
            pnlCriacaoModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCriacaoModulosLayout.setVerticalGroup(
            pnlCriacaoModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        lblTexto.setText("Texto");

        lblAudio.setText("Áudio");

        lblVideo.setText("Vídeo");

        lblTexto_Video.setText("Texto com Vídeo");

        lblVideo_Audio.setText("Vídeo com Áudio");

        lblTexto_Audio.setText("Texto com Áudio");

        lblVideo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vídeo.png"))); // NOI18N
        lblVideo_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblVideo_imgMouseReleased(evt);
            }
        });

        lblTexto_Video_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Texto e Vídeo.png"))); // NOI18N
        lblTexto_Video_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTexto_Video_imgMouseReleased(evt);
            }
        });

        lblTexto_Audio_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Texto e Áudio.png"))); // NOI18N
        lblTexto_Audio_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTexto_Audio_imgMouseReleased(evt);
            }
        });

        lblTexto_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Texto.png"))); // NOI18N
        lblTexto_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTexto_imgMouseReleased(evt);
            }
        });

        lblAudio_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Áudio.png"))); // NOI18N
        lblAudio_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAudio_imgMouseReleased(evt);
            }
        });

        lblVideo_Audio_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vídeo e Áudio.png"))); // NOI18N
        lblVideo_Audio_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblVideo_Audio_imgMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPrePosTesteLayout = new javax.swing.GroupLayout(pnlPrePosTeste);
        pnlPrePosTeste.setLayout(pnlPrePosTesteLayout);
        pnlPrePosTesteLayout.setHorizontalGroup(
            pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                        .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTexto_Video_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblTexto_Video)))
                        .addGap(50, 50, 50)
                        .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAudio_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTexto_Audio_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVideo_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVideo_Audio_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblTexto_Audio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVideo_Audio)
                                .addGap(56, 56, 56)))))
                .addGap(59, 59, Short.MAX_VALUE))
            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAudio)
                .addGap(223, 223, 223)
                .addComponent(lblVideo)
                .addGap(143, 143, 143))
        );
        pnlPrePosTesteLayout.setVerticalGroup(
            pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTexto_img)
                    .addComponent(lblAudio_img)
                    .addComponent(lblVideo_img))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto)
                    .addComponent(lblAudio)
                    .addComponent(lblVideo))
                .addGap(20, 20, 20)
                .addGroup(pnlPrePosTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                        .addComponent(lblVideo_Audio_img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVideo_Audio))
                    .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                        .addComponent(lblTexto_Video_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto_Video))
                    .addGroup(pnlPrePosTesteLayout.createSequentialGroup()
                        .addComponent(lblTexto_Audio_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto_Audio)))
                .addGap(30, 30, 30))
        );

        jtCriacaoModulos.addTab("Pré-Teste / Pós-Teste", pnlPrePosTeste);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCriacaoModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtCriacaoModulos, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPosTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeTeste)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtCriacaoModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreTeste, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lblPosTeste, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo)
                    .addComponent(btnCancelar))
                .addGap(1448, 1448, 1448)
                .addComponent(pnlCriacaoModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(190, 30, 839, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed

        if(teste.getTipo_form() == 0){
            JOptionPane.showMessageDialog(null, "Escolha uma das opções para o Pré-teste/Pós-teste!");
        }else{
            if(txtNomeTeste.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Dê um nome para identificar a atividade!");
            }else{
                switch(teste.getTipo_form()){
                    case 1:
                        //Set do tipo de form a ser chamado
                        EdicaoTesteTextoMDI edicaoModT = new EdicaoTesteTextoMDI();                 
                        edicaoModT.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneT = getDesktopPane();
                        desktopPaneT.add(edicaoModT);
                        edicaoModT.setVisible(true);
                        this.dispose();
                    break;
                    case 2:
                        EdicaoTesteAudioMDI edicaoModA = new EdicaoTesteAudioMDI();
                        edicaoModA.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneA = getDesktopPane();
                        desktopPaneA.add(edicaoModA);
                        edicaoModA.setVisible(true);
                        this.dispose();
                    break;
                    case 3:
                        EdicaoTesteVideoMDI edicaoModV = new EdicaoTesteVideoMDI();
                        edicaoModV.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneV = getDesktopPane();
                        desktopPaneV.add(edicaoModV);
                        edicaoModV.setVisible(true);
                        this.dispose();
                    break;
                    case 4:
                        EdicaoTesteTextoVideoMDI edicaoModTV = new EdicaoTesteTextoVideoMDI();
                        edicaoModTV.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneTV = getDesktopPane();
                        desktopPaneTV.add(edicaoModTV);
                        edicaoModTV.setVisible(true);
                        this.dispose();
                    break;
                    case 5:
                        EdicaoTesteTextoAudioMDI edicaoModTA = new EdicaoTesteTextoAudioMDI();
                        edicaoModTA.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneTA = getDesktopPane();
                        desktopPaneTA.add(edicaoModTA);
                        edicaoModTA.setVisible(true);
                        this.dispose();
                    break;
                    case 6:
                        EdicaoTesteVideoAudioMDI edicaoModVA = new EdicaoTesteVideoAudioMDI();
                        edicaoModVA.teste.setNome(txtNomeTeste.getText());

                        JDesktopPane desktopPaneVA = getDesktopPane();
                        desktopPaneVA.add(edicaoModVA);
                        edicaoModVA.setVisible(true);
                        this.dispose();
                    break;
                } 
            }
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void lblVideo_Audio_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideo_Audio_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Vídeo com Áudio");
        lblPosTeste.setText("Pós-Teste: Vídeo com Áudio");
        teste.setTipo_form(6);

        lblTexto_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Video_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_Audio_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
    }//GEN-LAST:event_lblVideo_Audio_imgMouseReleased

    private void lblAudio_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAudio_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Áudio");
        lblPosTeste.setText("Pós-Teste: Áudio");
        teste.setTipo_form(2);

        lblTexto_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblVideo_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Video_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));

    }//GEN-LAST:event_lblAudio_imgMouseReleased

    private void lblTexto_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTexto_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Texto");
        lblPosTeste.setText("Pós-Teste: Texto");
        teste.setTipo_form(1);

        lblTexto_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblVideo_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));;
        lblTexto_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Video_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
    }//GEN-LAST:event_lblTexto_imgMouseReleased

    private void lblTexto_Audio_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTexto_Audio_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Texto com Áudio");
        lblPosTeste.setText("Pós-Teste: Texto com Áudio");
        teste.setTipo_form(5);

        lblTexto_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Audio_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblTexto_Video_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
    }//GEN-LAST:event_lblTexto_Audio_imgMouseReleased

    private void lblTexto_Video_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTexto_Video_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Texto com Vídeo");
        lblPosTeste.setText("Pós-Teste: Texto com Vídeo");
        teste.setTipo_form(4);

        lblTexto_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Video_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblVideo_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
    }//GEN-LAST:event_lblTexto_Video_imgMouseReleased

    private void lblVideo_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideo_imgMouseReleased
        lblPreTeste.setText("Pré-Teste: Vídeo");
        lblPosTeste.setText("Pós-Teste: Vídeo");
        teste.setTipo_form(3);

        lblTexto_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblAudio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblTexto_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblTexto_Video_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
        lblVideo_Audio_img.setBorder(new MatteBorder(0,0,0,0,Color.BLACK));
    }//GEN-LAST:event_lblVideo_imgMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jtCriacaoModulos;
    private javax.swing.JLabel lblAudio;
    private javax.swing.JLabel lblAudio_img;
    private javax.swing.JLabel lblPosTeste;
    private javax.swing.JLabel lblPreTeste;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTexto_Audio;
    private javax.swing.JLabel lblTexto_Audio_img;
    private javax.swing.JLabel lblTexto_Video;
    private javax.swing.JLabel lblTexto_Video_img;
    private javax.swing.JLabel lblTexto_img;
    private javax.swing.JLabel lblVideo;
    private javax.swing.JLabel lblVideo_Audio;
    private javax.swing.JLabel lblVideo_Audio_img;
    private javax.swing.JLabel lblVideo_img;
    private javax.swing.JPanel pnlCriacaoModulos;
    private javax.swing.JPanel pnlPrePosTeste;
    private javax.swing.JTextField txtNomeTeste;
    // End of variables declaration//GEN-END:variables
}
