/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import model.beans.Ensino;

/**
 *
 * @author Vinicius
 */
public class CriacaoEnsinoMDI extends javax.swing.JInternalFrame {
    /**
     * Creates new form CriacaoModMDI
     */
    public CriacaoEnsinoMDI() {
        initComponents();
    }
    Ensino ensino = new Ensino();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProximo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblEnsino = new javax.swing.JLabel();
        jtCriacaoModulos = new javax.swing.JTabbedPane();
        pnlEnsino = new javax.swing.JPanel();
        lblVideoE_img = new javax.swing.JLabel();
        lblTextoE = new javax.swing.JLabel();
        lblAudioE = new javax.swing.JLabel();
        lblVideoE = new javax.swing.JLabel();
        lblTextoE_img = new javax.swing.JLabel();
        lblAudioE_img = new javax.swing.JLabel();
        txtNomeEnsino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criação de Atividades (Ensino)");

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblEnsino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEnsino.setText("Ensino:");

        pnlEnsino.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVideoE_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VideoMOD.png"))); // NOI18N
        lblVideoE_img.setBorder(new javax.swing.border.MatteBorder(null));
        lblVideoE_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblVideoE_imgMouseReleased(evt);
            }
        });
        pnlEnsino.add(lblVideoE_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 130, 130));

        lblTextoE.setText("Texto");
        pnlEnsino.add(lblTextoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        lblAudioE.setText("Áudio");
        pnlEnsino.add(lblAudioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        lblVideoE.setText("Vídeo");
        pnlEnsino.add(lblVideoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        lblTextoE_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextoMOD.png"))); // NOI18N
        lblTextoE_img.setBorder(new javax.swing.border.MatteBorder(null));
        lblTextoE_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTextoE_imgMouseReleased(evt);
            }
        });
        pnlEnsino.add(lblTextoE_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 130));

        lblAudioE_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AudioMOD.png"))); // NOI18N
        lblAudioE_img.setBorder(new javax.swing.border.MatteBorder(null));
        lblAudioE_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAudioE_imgMouseReleased(evt);
            }
        });
        pnlEnsino.add(lblAudioE_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, 130));

        jtCriacaoModulos.addTab("Ensino", pnlEnsino);

        txtNomeEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEnsinoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(btnProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jtCriacaoModulos, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtCriacaoModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnCancelar)
                    .addComponent(lblEnsino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(467, 467, 467))
        );

        setBounds(190, 30, 839, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed

        if(ensino.getTipo_form() == 0){
            JOptionPane.showMessageDialog(null, "Escolha uma das opções para o Ensino!"); 
        }else{
            if(txtNomeEnsino.getText().equals("")){
                
                JOptionPane.showMessageDialog(null,"Dê um nome para identificar a atividade!");
            }else{
                switch(ensino.getTipo_form()){
                    case 1:
                        EdicaoEnsinoTextoMDI ensinoT = new EdicaoEnsinoTextoMDI();
                        ensinoT.ensino.setNome(txtNomeEnsino.getText());
                        
                        JDesktopPane desktopPaneT = getDesktopPane();
                        desktopPaneT.add(ensinoT);
                        ensinoT.setVisible(true);
                        
                        this.dispose();
                    break;
                    case 2:
                        EdicaoEnsinoAudioMDI ensinoA = new EdicaoEnsinoAudioMDI();
                        ensinoA.ensino.setNome(txtNomeEnsino.getText());
                        
                        JDesktopPane desktopPaneA = getDesktopPane();
                        desktopPaneA.add(ensinoA);
                        ensinoA.setVisible(true);
                        this.dispose();
                    break;
                    case 3:
                        EdicaoEnsinoVideoMDI ensinoV = new EdicaoEnsinoVideoMDI();
                        ensinoV.ensino.setNome(txtNomeEnsino.getText());
                        
                        JDesktopPane desktopPaneV = getDesktopPane();
                        desktopPaneV.add(ensinoV);
                        ensinoV.setVisible(true);
                        this.dispose();
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void lblAudioE_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAudioE_imgMouseReleased
        lblEnsino.setText("Ensino: Áudio");
        ensino.setTipo_form(2);

        lblTextoE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
        lblAudioE_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblVideoE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
    }//GEN-LAST:event_lblAudioE_imgMouseReleased

    private void lblTextoE_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextoE_imgMouseReleased
        lblEnsino.setText("Ensino: Texto");
        ensino.setTipo_form(1);
        
        lblTextoE_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblAudioE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
        lblVideoE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
    }//GEN-LAST:event_lblTextoE_imgMouseReleased

    private void lblVideoE_imgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideoE_imgMouseReleased
        lblEnsino.setText("Ensino: Vídeo");
        ensino.setTipo_form(3);

        lblTextoE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
        lblAudioE_img.setBorder(new MatteBorder(0,0,0,0, Color.BLACK));
        lblVideoE_img.setBorder(new MatteBorder(3,3,3,3,Color.RED));
    }//GEN-LAST:event_lblVideoE_imgMouseReleased

    private void txtNomeEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEnsinoActionPerformed
        
    }//GEN-LAST:event_txtNomeEnsinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jtCriacaoModulos;
    private javax.swing.JLabel lblAudioE;
    private javax.swing.JLabel lblAudioE_img;
    private javax.swing.JLabel lblEnsino;
    private javax.swing.JLabel lblTextoE;
    private javax.swing.JLabel lblTextoE_img;
    private javax.swing.JLabel lblVideoE;
    private javax.swing.JLabel lblVideoE_img;
    private javax.swing.JPanel pnlEnsino;
    private javax.swing.JTextField txtNomeEnsino;
    // End of variables declaration//GEN-END:variables
}
