/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import model.beans.Ensino;
import model.dao.EnsinoDAO;

/**
 *
 * @author Vinicius
 */
public class EdicaoEnsinoAudioMDI extends javax.swing.JInternalFrame {

    /**
     * Creates new form EdicaoEnsinoAudioMDI
     */
    public EdicaoEnsinoAudioMDI() {
        initComponents();
    }
    Ensino ensino = new Ensino();
    EnsinoDAO dao = new EnsinoDAO();
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEnsinoAudio = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtYoutube = new javax.swing.JTextField();
        lblYoutube = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Edição de Módulos - Ensino (Áudio)");
        setToolTipText("");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblYoutube.setText("Link do Youtube (Áudio): ");

        javax.swing.GroupLayout pnlEnsinoAudioLayout = new javax.swing.GroupLayout(pnlEnsinoAudio);
        pnlEnsinoAudio.setLayout(pnlEnsinoAudioLayout);
        pnlEnsinoAudioLayout.setHorizontalGroup(
            pnlEnsinoAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnsinoAudioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnsinoAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEnsinoAudioLayout.createSequentialGroup()
                        .addGap(0, 647, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(10, 10, 10)
                        .addComponent(btnCancelar))
                    .addGroup(pnlEnsinoAudioLayout.createSequentialGroup()
                        .addComponent(lblYoutube)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYoutube)))
                .addGap(43, 43, 43))
        );
        pnlEnsinoAudioLayout.setVerticalGroup(
            pnlEnsinoAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnsinoAudioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlEnsinoAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYoutube, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYoutube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEnsinoAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnsinoAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnsinoAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(190, 30, 864, 133);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       ensino.setTipo_form(2);
       ensino.setTexto(null);
       ensino.setEnd_audio(txtYoutube.getText());
       ensino.setEnd_video(null);
       
       if(!ensino.isEdit()){
            JDesktopPane desktopPaneT = getDesktopPane();
            JInternalFrame [] l = desktopPaneT.getAllFrames();
            for (int i = 0; i < l.length; i++) 
                if (l[i].getClass() == CriacaoModulosMDI.class) {
                    CriacaoModulosMDI criacaoMod = (CriacaoModulosMDI) l[i];
                    criacaoMod.insereNovaLinhaEnsino(ensino);
                    break;
                }
       }
       this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblYoutube;
    private javax.swing.JPanel pnlEnsinoAudio;
    private javax.swing.JTextField txtYoutube;
    // End of variables declaration//GEN-END:variables
}
