/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.beans.AtividadeModulo;
import model.beans.Ensino;
import model.beans.Historico;
import model.beans.Testes;
import model.beans.Usuario;
import model.dao.AtividadeModuloDAO;
import model.dao.EnsinoDAO;
import model.dao.HistoricoDAO;
import model.dao.TestesDAO;

/**
 *
 * @author Vinicius
 */
public class EnsinoAudioMDI extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form EdicaoEnsinoTextoMDI
     */
    public EnsinoAudioMDI() {
        initComponents();
    }
    Usuario user = new Usuario();
    Historico hist = new Historico();
    HistoricoDAO hist_dao = new HistoricoDAO();
    Ensino ensino = new Ensino();
    EnsinoDAO dao = new EnsinoDAO();
    Testes teste = new Testes();
    TestesDAO teste_dao = new TestesDAO();
    AtividadeModulo ativ_mod = new AtividadeModulo();
    AtividadeModuloDAO ativ_mod_dao = new AtividadeModuloDAO();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEnsinoTexto = new javax.swing.JPanel();
        lblAudio = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Módulos - Ensino (Áudio)");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lblAudio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAudio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAudio.setText("COLOCAR AUDIO AQUI!");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnOk.setText("OK!");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnsinoTextoLayout = new javax.swing.GroupLayout(pnlEnsinoTexto);
        pnlEnsinoTexto.setLayout(pnlEnsinoTextoLayout);
        pnlEnsinoTextoLayout.setHorizontalGroup(
            pnlEnsinoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnsinoTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
            .addGroup(pnlEnsinoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEnsinoTextoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblAudio)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlEnsinoTextoLayout.setVerticalGroup(
            pnlEnsinoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnsinoTextoLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(pnlEnsinoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap())
            .addGroup(pnlEnsinoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEnsinoTextoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblAudio)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnsinoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnsinoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(190, 30, 581, 247);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        hist.setCpf(user.getCpf());
        hist.setId_grupo(1);
        hist.setId_modulo(ativ_mod.getId_modulo());
        hist.setOrdem(ativ_mod.getOrdem());
        hist.setStatus_ativ("P");
        hist.setResposta(null);
        hist.setFase("ENS");
        
        hist_dao.cadastrar(hist);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        ativ_mod = ativ_mod_dao.consultaAnt(ativ_mod);
        
        if(ativ_mod.getId_teste() != 0){
            teste.setId_teste(ativ_mod.getId_teste());
            teste = teste_dao.popular(teste);
            
            JOptionPane.showMessageDialog(null, "ID_Teste: "+ativ_mod.getId_teste());
            JOptionPane.showMessageDialog(null, "Tipo form: "+teste.getTipo_form());
                
            teste.setEdit(false);
            switch(teste.getTipo_form()){
                case 1:
                    //Set do tipo de form a ser chamado
                    TesteTextoMDI ModT = new TesteTextoMDI();                 
                    ModT.teste = this.teste;
                    ModT.ativ_mod = this.ativ_mod;
                    ModT.user = this.user;
                    ModT.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneT = getDesktopPane();
                    desktopPaneT.add(ModT);
                    ModT.setVisible(true);
                break;
                case 2:
                    TesteAudioMDI ModA = new TesteAudioMDI();
                    ModA.teste = this.teste;
                    ModA.ativ_mod = this.ativ_mod;
                    ModA.user = this.user;
                    ModA.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneA = getDesktopPane();
                    desktopPaneA.add(ModA);
                    ModA.setVisible(true);
                break;
                case 3:
                    TesteVideoMDI ModV = new TesteVideoMDI();
                    ModV.teste = this.teste;
                    ModV.ativ_mod = this.ativ_mod;
                    ModV.user = this.user;
                    ModV.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneV = getDesktopPane();
                    desktopPaneV.add(ModV);
                    ModV.setVisible(true);
                break;
                case 4:
                    TesteTextoVideoMDI ModTV = new TesteTextoVideoMDI();
                    ModTV.teste = this.teste;
                    ModTV.ativ_mod = this.ativ_mod;
                    ModTV.user = this.user;
                    ModTV.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneTV = getDesktopPane();
                    desktopPaneTV.add(ModTV);
                    ModTV.setVisible(true);
                break;
                case 5:
                    TesteTextoAudioMDI ModTA = new TesteTextoAudioMDI();
                    ModTA.teste = this.teste;
                    ModTA.ativ_mod = this.ativ_mod;
                    ModTA.user = this.user;
                    ModTA.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneTA = getDesktopPane();
                    desktopPaneTA.add(ModTA);
                    ModTA.setVisible(true);
                break;
                case 6:
                    TesteVideoAudioMDI ModVA = new TesteVideoAudioMDI();
                    ModVA.teste = this.teste;
                    ModVA.ativ_mod = this.ativ_mod;
                    ModVA.user = this.user;
                    ModVA.mod.setPrepos(1);
                    
                    JDesktopPane desktopPaneVA = getDesktopPane();
                    desktopPaneVA.add(ModVA);
                    ModVA.setVisible(true);
                break;
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       JOptionPane.showMessageDialog(null, "Módulo: "+ativ_mod.getId_modulo()+
                                            "\nOrdem: "+ativ_mod.getOrdem());
        
        if(!ensino.isEdit()){
           ensino = dao.popular(ensino);
           btnOk.setVisible(false);
       }else{
           btnProximo.setVisible(false);
           btnCancelar.setVisible(false);
       }
        lblAudio.setText(ensino.getEnd_audio());       

    }//GEN-LAST:event_formInternalFrameOpened

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel lblAudio;
    private javax.swing.JPanel pnlEnsinoTexto;
    // End of variables declaration//GEN-END:variables
}
