/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.beans.AtividadeModulo;
import model.beans.Modulo;
import model.beans.Testes;
import model.beans.Usuario;
import model.dao.AtividadeModuloDAO;
import model.dao.ModuloDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author Vinicius
 */
public class TelaPrincipalUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalUser
     */
    public TelaPrincipalUser() {
        initComponents();
    }
    UsuarioDAO dao = new UsuarioDAO();
    Usuario user = new Usuario();
    Testes teste = new Testes();
    ModuloDAO mod_dao = new ModuloDAO();
    AtividadeModuloDAO ativ_mod_dao = new AtividadeModuloDAO();
    AtividadeModulo ativ_mod = new AtividadeModulo();
    Modulo mod = new Modulo();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPPrincipal = new javax.swing.JDesktopPane();
        txtNome = new javax.swing.JLabel();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenuItem();
        jMISearch = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();
        jMMódulos = new javax.swing.JMenu();
        jmAtividades = new javax.swing.JMenuItem();
        jMConfig = new javax.swing.JMenu();
        jMUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Tela Principal Usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDPPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDPPrincipalMouseReleased(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jDPPrincipal.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPPrincipalLayout = new javax.swing.GroupLayout(jDPPrincipal);
        jDPPrincipal.setLayout(jDPPrincipalLayout);
        jDPPrincipalLayout.setHorizontalGroup(
            jDPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDPPrincipalLayout.createSequentialGroup()
                .addGap(0, 850, Short.MAX_VALUE)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDPPrincipalLayout.setVerticalGroup(
            jDPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPPrincipalLayout.createSequentialGroup()
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 549, Short.MAX_VALUE))
        );

        jMArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        jMArquivo.setText("Arquivo");

        jMSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMSobre.setText("Sobre");
        jMSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSobreActionPerformed(evt);
            }
        });
        jMArquivo.add(jMSobre);

        jMISearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMISearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        jMISearch.setText("Pesquisar");
        jMArquivo.add(jMISearch);

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMISair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMArquivo.add(jMISair);

        jMBPrincipal.add(jMArquivo);

        jMMódulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/application.png"))); // NOI18N
        jMMódulos.setText("Módulos");

        jmAtividades.setText("Atividades");
        jmAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAtividadesActionPerformed(evt);
            }
        });
        jMMódulos.add(jmAtividades);

        jMBPrincipal.add(jMMódulos);

        jMConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrench.png"))); // NOI18N
        jMConfig.setText("Configurações");

        jMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMUser.setText("Usuário");
        jMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUserActionPerformed(evt);
            }
        });
        jMConfig.add(jMUser);

        jMBPrincipal.add(jMConfig);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPPrincipal)
        );

        setSize(new java.awt.Dimension(1216, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSobreActionPerformed
        SobreMDI sobre = new SobreMDI();
        jDPPrincipal.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMSobreActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        // jMenuItem Sair Tela Principal
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMISairActionPerformed

    private void jDPPrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDPPrincipalMouseReleased

    }//GEN-LAST:event_jDPPrincipalMouseReleased

    private void jMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUserActionPerformed
        ConfigUsuarioMDI configUser = new ConfigUsuarioMDI();
        configUser.user.setUserCnfg(this.user.getUserLog());

        jDPPrincipal.add(configUser);
        configUser.setVisible(true);
    }//GEN-LAST:event_jMUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String Nome = dao.usuarioAtivo(user.getUserLog());
        txtNome.setText("Bem vindo(a), " + Nome);
        user = dao.popular(user.getUserLog()); 
    }//GEN-LAST:event_formWindowOpened

    private void jmAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAtividadesActionPerformed
        AtividadesMDI atividades = new AtividadesMDI();
        atividades.user = this.user;
        atividades.user.setUserLog(this.user.getUserLog());
        jDPPrincipal.add(atividades);
        atividades.setVisible(true);
    }//GEN-LAST:event_jmAtividadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPPrincipal;
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMConfig;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMISearch;
    private javax.swing.JMenu jMMódulos;
    private javax.swing.JMenuItem jMSobre;
    private javax.swing.JMenuItem jMUser;
    private javax.swing.JMenuItem jmAtividades;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
