/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.beans.Grupo;
import model.beans.UsuarioGrupo;
import model.dao.GrupoDAO;

/**
 *
 * @author Vinicius
 */
public class TelaCadastroGrupoMDI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroGrupoMDI
     */
    public TelaCadastroGrupoMDI() {
        initComponents();
    }
    
    Grupo grupo = new Grupo();
    GrupoDAO dao = new GrupoDAO();
    UsuarioGrupo ugrupo = new UsuarioGrupo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCadastarG = new javax.swing.JButton();
        btnCancelarG = new javax.swing.JButton();
        lblNomeEscola = new javax.swing.JLabel();
        txtNomeEscola = new javax.swing.JTextField();
        lblMunicipio = new javax.swing.JLabel();
        txtNomeGrupo = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        rbControle = new javax.swing.JRadioButton();
        rbExperimental = new javax.swing.JRadioButton();
        lblChave = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro do grupo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do grupo"));

        btnCadastarG.setText("Cadastrar");
        btnCadastarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastarGActionPerformed(evt);
            }
        });

        btnCancelarG.setText("Cancelar");
        btnCancelarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGActionPerformed(evt);
            }
        });

        lblNomeEscola.setText("Escola");

        lblMunicipio.setText("Nome do Grupo");

        lblGrupo.setText("Grupo: ");

        bgGrupo.add(rbControle);
        rbControle.setText("Controle");
        rbControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbControleActionPerformed(evt);
            }
        });

        bgGrupo.add(rbExperimental);
        rbExperimental.setText("Experimental");

        lblChave.setText("Chave Secreta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblNomeEscola)
                .addGap(18, 18, 18)
                .addComponent(txtNomeEscola, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMunicipio)
                    .addComponent(lblChave))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbControle))
                    .addComponent(btnCadastarG, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbExperimental)
                    .addComponent(btnCancelarG)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEscola)
                    .addComponent(txtNomeEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMunicipio)
                    .addComponent(txtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupo)
                    .addComponent(rbControle)
                    .addComponent(rbExperimental))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastarG)
                    .addComponent(btnCancelarG)
                    .addComponent(lblChave)
                    .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        setBounds(280, 30, 626, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarGActionPerformed

    private void rbControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbControleActionPerformed
        
    }//GEN-LAST:event_rbControleActionPerformed

    private void btnCadastarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastarGActionPerformed
        grupo.setNome_escola(txtNomeEscola.getText());
        grupo.setNome_grupo(txtNomeGrupo.getText());
        grupo.setChave_secreta(txtChave.getText());
        if(rbControle.isSelected()){
            grupo.setTipo_grupo("C");
        }
        if(rbExperimental.isSelected()){
            grupo.setTipo_grupo("E");
        }
        dao.cadastrarGrupo(grupo);
        this.dispose();              
    }//GEN-LAST:event_btnCadastarGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupo;
    private javax.swing.JButton btnCadastarG;
    private javax.swing.JButton btnCancelarG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChave;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNomeEscola;
    private javax.swing.JRadioButton rbControle;
    private javax.swing.JRadioButton rbExperimental;
    private javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtNomeEscola;
    private javax.swing.JTextField txtNomeGrupo;
    // End of variables declaration//GEN-END:variables
}
