/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author wfranca
 */
public class Timeline extends javax.swing.JFrame {
    int atu = 0;
    String troca;
    /**
     * Creates new form Timeline
     */
    public Timeline() {
        initComponents();
        btnDir.setEnabled(false);
        btnEsq.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVisor = new javax.swing.JLabel();
        plnTimeline = new javax.swing.JPanel();
        lblt1 = new javax.swing.JLabel();
        lblt2 = new javax.swing.JLabel();
        lblt3 = new javax.swing.JLabel();
        lblt4 = new javax.swing.JLabel();
        lblt5 = new javax.swing.JLabel();
        btnDir = new javax.swing.JButton();
        btnEsq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timeline de MODS");

        lblVisor.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblVisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        plnTimeline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plnTimeline.setAutoscrolls(true);

        lblt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblt1.setText("jLabel1");
        lblt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblt1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblt1MouseReleased(evt);
            }
        });

        lblt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblt2.setText("jLabel2");
        lblt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblt2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblt2MouseReleased(evt);
            }
        });

        lblt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblt3.setText("jLabel3");
        lblt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblt3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblt3MouseReleased(evt);
            }
        });

        lblt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblt4.setText("jLabel4");
        lblt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblt4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblt4MouseReleased(evt);
            }
        });

        lblt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblt5.setText("jLabel5");
        lblt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblt5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblt5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout plnTimelineLayout = new javax.swing.GroupLayout(plnTimeline);
        plnTimeline.setLayout(plnTimelineLayout);
        plnTimelineLayout.setHorizontalGroup(
            plnTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTimelineLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblt1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblt2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblt3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblt4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblt5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        plnTimelineLayout.setVerticalGroup(
            plnTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnTimelineLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(plnTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(plnTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblt5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblt4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        btnDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control_end_blue.png"))); // NOI18N
        btnDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirActionPerformed(evt);
            }
        });

        btnEsq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control_start_blue.png"))); // NOI18N
        btnEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(plnTimeline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnDir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEsq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plnTimeline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirActionPerformed
       switch(atu){
           case 1:
               troca = lblt1.getText();
               lblt1.setText(lblt2.getText());
               lblt2.setText(troca);
               atu = 2;
               lblVisor.setText("" + atu);
               lblt1.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt2.setBorder(new MatteBorder(3,3,3,3,Color.RED));
               btnEsq.setEnabled(true);
           break;
           case 2:
               troca = lblt2.getText();
               lblt2.setText(lblt3.getText());
               lblt3.setText(troca);
               atu = 3;
               lblVisor.setText("" + atu);
               lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt3.setBorder(new MatteBorder(3,3,3,3,Color.RED));
           break;
           case 3:
               troca = lblt3.getText();
               lblt3.setText(lblt4.getText());
               lblt4.setText(troca);
               atu = 4;
               lblVisor.setText("" + atu);
               lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt4.setBorder(new MatteBorder(3,3,3,3,Color.RED));
           break;
           case 4:
               troca = lblt4.getText();
               lblt4.setText(lblt5.getText());
               lblt5.setText(troca);
               atu = 5;
               lblVisor.setText("" + atu);
               lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt5.setBorder(new MatteBorder(3,3,3,3,Color.RED));
               btnDir.setEnabled(false);
           break;
       }
    }//GEN-LAST:event_btnDirActionPerformed

    private void btnEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqActionPerformed
        switch(atu){
           case 2:
               troca = lblt1.getText();
               lblt1.setText(lblt2.getText());
               lblt2.setText(troca);
               atu = 1;
               lblVisor.setText("" + atu);
               lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt1.setBorder(new MatteBorder(3,3,3,3,Color.RED));
               btnEsq.setEnabled(false);
           break;
           case 3:
               troca = lblt2.getText();
               lblt2.setText(lblt3.getText());
               lblt3.setText(troca);
               atu = 2;
               lblVisor.setText("" + atu);
               lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt2.setBorder(new MatteBorder(3,3,3,3,Color.RED));
           break;
           case 4:
               troca = lblt3.getText();
               lblt3.setText(lblt4.getText());
               lblt4.setText(troca);
               atu = 3;
               lblVisor.setText("" + atu);
               lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt3.setBorder(new MatteBorder(3,3,3,3,Color.RED));
           break;
           case 5:
               troca = lblt4.getText();
               lblt4.setText(lblt5.getText());
               lblt5.setText(troca);
               atu = 4;
               lblVisor.setText("" + atu);
               lblt5.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
               lblt4.setBorder(new MatteBorder(3,3,3,3,Color.RED));
               btnDir.setEnabled(true);
           break;
       }
    }//GEN-LAST:event_btnEsqActionPerformed

    private void lblt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblt1MouseReleased
        lblt1.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt5.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        btnEsq.setEnabled(false);
        btnDir.setEnabled(true);
        atu = 1;
        lblVisor.setText("" + atu);
    }//GEN-LAST:event_lblt1MouseReleased

    private void lblt2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblt2MouseReleased
        lblt1.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt2.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt5.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        btnEsq.setEnabled(true);
        btnDir.setEnabled(true);
        atu = 2;
        lblVisor.setText("" + atu);
    }//GEN-LAST:event_lblt2MouseReleased

    private void lblt3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblt3MouseReleased
        lblt1.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt3.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt5.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        btnEsq.setEnabled(true);
        btnDir.setEnabled(true);
        atu = 3;
        lblVisor.setText("" + atu);
    }//GEN-LAST:event_lblt3MouseReleased

    private void lblt4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblt4MouseReleased
        lblt1.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt4.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        lblt5.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        btnEsq.setEnabled(true);
        btnDir.setEnabled(true);
        atu = 4;
        lblVisor.setText("" + atu);
    }//GEN-LAST:event_lblt4MouseReleased

    private void lblt5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblt5MouseReleased
        lblt1.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt2.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt3.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt4.setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
        lblt5.setBorder(new MatteBorder(3,3,3,3,Color.RED));
        btnEsq.setEnabled(true);
        btnDir.setEnabled(false);
        atu = 5;
        lblVisor.setText("" + atu);
    }//GEN-LAST:event_lblt5MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timeline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDir;
    private javax.swing.JButton btnEsq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblVisor;
    private javax.swing.JLabel lblt1;
    private javax.swing.JLabel lblt2;
    private javax.swing.JLabel lblt3;
    private javax.swing.JLabel lblt4;
    private javax.swing.JLabel lblt5;
    private javax.swing.JPanel plnTimeline;
    // End of variables declaration//GEN-END:variables
}
